---
- name: Install clickhouse server and web
  hosts: clickhouse
  become: true
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
  roles:
    # - role: buluma.bootstrap
    # - role: buluma.selinux
    # - role: robertdebock.container_docs
    # - role: buluma.buildtools
    # - role: buluma.epel
    # - role: buluma.python_pip
    # - role: buluma.openssl
    #   openssl_items:
    #     - name: apache-httpd
    #       common_name: "{{ ansible_fqdn }}"
    - role: buluma.mysql
      mysql_databases:
        - name: clickhouse
          encoding: utf8
          collation: utf8_bin
      mysql_users:
        - name: clickhouse
          password: clickhouse
          priv: "clickhouse.*:ALL"
    - role: buluma.php
    - role: buluma.httpd
    # - role: buluma.ca_certificates
    - role: buluma.clickhouse_repository
    # - role: buluma.core_dependencies
    - role: buluma.clickhouse_server

    - role: buluma.clickhouse_web
      # You can provision clickhouse groups.
      # Most options map directly to the documentation:
      # https://docs.ansible.com/ansible/latest/modules/clickhouse_group_module.html
      clickhouse_web_groups:
        - name: Linux servers
