---
- hosts: consul_instances
  become: true
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
  roles:
    - role: ansible-consul
  vars:
    consul_checksum_file_url: "https://hc-mirror.express42.net/consul/{{ consul_version }}/consul_{{ consul_version}}_SHA256SUMS"
    consul_zip_url: "https://hc-mirror.express42.net/consul/{{ consul_version }}/consul_{{ consul_version }}_{{ consul_os }}_{{ consul_architecture }}.zip"
