---
- hosts: vm-single
  collections:
    - victoriametrics.cluster
  become: true
  roles:
    - role: cloudalchemy.node_exporter
    - role: victoriametrics.cluster.vmagent
    - role: victoriametrics.cluster.single
    - role: buluma.grafana
