---
- name: Install zabbix server and web
  hosts: zabbix
  become: true
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
    - name: Remove 127.0.1.1 from /etc/hosts
      lineinfile:
        path: /etc/hosts
        state: absent
        regexp: '^127.0.1.1'
    - name: Reboot host and wait for it to restart
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
  roles:
    # - role: buluma.bootstrap
    # - role: buluma.selinux
    # - role: robertdebock.container_docs
    # - role: buluma.buildtools
    # - role: buluma.epel
    - role: buluma.python_pip
    # - role: buluma.openssl
    #   openssl_items:
    #     - name: apache-httpd
    #       common_name: "{{ ansible_fqdn }}"
    - role: buluma.mysql
      mysql_databases:
        - name: zabbix
          encoding: utf8
          collation: utf8_bin
      mysql_users:
        - name: zabbix
          password: zabbix
          priv: "zabbix.*:ALL"
    - role: buluma.php
    - role: buluma.httpd
    # - role: buluma.ca_certificates
    - role: buluma.zabbix_repository
    # - role: buluma.core_dependencies
    - role: buluma.zabbix_server

    - role: buluma.zabbix_web
      # You can provision Zabbix groups.
      # Most options map directly to the documentation:
      # https://docs.ansible.com/ansible/latest/modules/zabbix_group_module.html
      zabbix_web_groups:
        - name: Linux servers
