---
- hosts: vault_raft_servers
  become: true
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
  roles:
    - role: robertdebock.core_dependencies
    - role: robertdebock.hashicorp
      hashicorp_installation_method: manual
      binary_repo: hc-mirror.express42.net
      hashicorp_products:
        - name: vault
          version: "1.9.4"
          type: oss
      _hashicorp_src:
        oss: "https://hc-mirror.express42.net/{{ item.name }}/{{ item.version }}/{{ item.name }}_{{ item.version }}_linux_{{ hashicorp_architecture_mapping }}.zip"
    - role: robertdebock.vault
      vault_show_unseal_information: yes
      vault_install_package: no
      vault_store_root_token: yes
      vault_make_backup: yes
      vault_kv_secrets:
        - name: my-secret
          data:
            foo: bar
            zip: zap
  # vars:
    # vault_checksum_file_url: "https://hc-mirror.express42.net/vault/{{ vault_version }}/vault_{{ vault_version}}_SHA256SUMS"
    # vault_zip_url: "https://hc-mirror.express42.net/vault/{{ vault_version }}/vault_{{ vault_version }}_{{ vault_os }}_{{ vault_architecture }}.zip"
