---
- hosts: vault_raft_servers
  become: true
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
  roles:
    - role: ansible-vault
  vars:
    vault_checksum_file_url: "https://hc-mirror.express42.net/vault/{{ vault_version }}/vault_{{ vault_version}}_SHA256SUMS"
    vault_zip_url: "https://hc-mirror.express42.net/vault/{{ vault_version }}/vault_{{ vault_version }}_{{ vault_os }}_{{ vault_architecture }}.zip"

    # vault_backend: file
    vault_log_level: debug
    vault_backend: raft
    # vault_seal_generate_key: True
    # vault_raft_node_id: "{{ ansible_facts.nodename }}"
    # vault_api_addr: "{{ vault_protocol }}://{{ ansible_facts.nodename }}:{{ vault_port }}"
    # vault_address: "{{ ansible_facts.nodename }}"
    # vault_cluster_addr: "{{ vault_protocol }}://{{ ansible_facts.nodename }}"
    # vault_port: 8200
