---
- hosts: javaindocker
  become: true
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
    - name: install pip3
      apt: name=python3-pip state=present
  roles:
    - role: buluma.java
    - role: geerlingguy.docker
    # - role: cloudalchemy.node_exporter
    - role: andrewrothstein.prometheus_jmx_exporter
  post_tasks:
    - name: Install multi python packages with version specifiers
      pip:
        name:
          - docker
          - docker-compose
    - name: Git checkout e2e Repository 
      ansible.builtin.git:
        repo: 'https://github.com/Drill4J/e2e.git'
        dest: e2e
    # use files parameter to use multiple docker-compose.yml files
    - name: Run docker-compose.admin up
      community.general.docker_compose:
        project_src: e2e/docker
        files:
          - docker-compose.admin.yml

- name: Install prometheus and Grafana
  become: true
  hosts: prometheus
  roles:
    # - role: cloudalchemy.node_exporter
    - role: buluma.prometheus
      vars:
        prometheus_targets:
          node:
          - targets:
            - localhost:9100
        prometheus_components: [ "prometheus", "node_exporter" ]
    - role: buluma.grafana
      vars:
        grafana_use_provisioning: true
        grafana_security:
          admin_user: admin
          admin_password: enter_your_secure_password
        grafana_datasources:
          - name: prometheus
            type: prometheus
            access: proxy
            url: 'http://localhost:9090'
            basicAuth: false
        grafana_dashboards:
        - dashboard_id: 1860
          revision_id: 26
          datasource: prometheus

# https://github.com/stadtulm/a13-ansible/blob/master/main.yml