---
- hosts: javaindocker
  become: true
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
    - name: install pip3
      apt: name=python3-pip state=present
  roles:
    - role: buluma.java
      vars:
        java_type: jdk
        java_version: "8"
  post_tasks:
    - name: install maven
      apt: name=maven state=present


- name: Install prometheus and Grafana
  become: true
  hosts: prometheus
  roles:
    - role: cloudalchemy.node_exporter
    - role: cloudalchemy.prometheus
    - role: buluma.grafana


# https://github.com/stadtulm/a13-ansible/blob/master/main.yml