---
- name: Install prometheus and Grafana
  hosts: prometheus
  roles:
    - role: cloudalchemy.node_exporter
    - role: cloudalchemy.prometheus
      vars:
        prometheus_targets:
          node:
          - targets:
            - localhost:9100
    - role: cloudalchemy.grafana
      vars:
        grafana_dashboards: [1860]
        grafana_security:
          admin_user: admin
          admin_password: enter_your_secure_password
        grafana_datasources:
          - name: prometheus
            type: prometheus
            access: proxy
            url: 'http://localhost:9090'
            basicAuth: false