  - hosts: sonarqube
    become: yes
    pre_tasks:
      - name: Install package dependencies.
        package:
          name: "{{ item }}"
          state: "present"
        with_items:
          - unzip
    roles:
      - buluma.java
      - lrk.sonarqube